version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: stylino_db
      POSTGRES_USER: stylino
      POSTGRES_PASSWORD: stylino
    ports:
      - "5432:5432"
    volumes:
      - stylino_db_data:/var/lib/postgresql/data

volumes:
  stylino_db_data:
