version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: stylino_root
      MYSQL_DATABASE: stylino_db
      MYSQL_USER: stylino
      MYSQL_PASSWORD: stylino
    ports:
      - "3306:3306"
    volumes:
      - stylino_mysql_data:/var/lib/mysql

volumes:
  stylino_mysql_data:
